# Site settings
title:
email: Weow Music
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/Zwaper" # the subpath of your site, e.g. /blog/
url: "http://weowmusic.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: Zwaper

# Build settings
markdown: kramdown
